### ISSUE TITLE
workflow/pipeline to get from altium to blender

### ISSUE THREAD

**Issue by raveslave** [PCB-Arts/stylized-blender-setup#2]
hi!

may I ask what's your pipeline when exporting these from altium? 
a script, outjob or manual?

thx

**Comment by lukashenkel** [comment]
Hi,

We used an outjob to export a PDF file with the corresponding layers. With Gimp we generated textures with the desired resolution.

**Comment by raveslave** [comment]
thanks. how about the via's?

**Comment by lukashenkel** [comment]
You can export your PCB with the IDF export option in Altium. This 3D model also contains the VIAs. We merge the IDF Board export with the STEP export in our CAD tool to get a realistic 3D model.
